### ISSUE TITLE
Got a conflicting result

### ISSUE THREAD

**Issue by Wilbur529** [GuoleiSun/CountSeg#3]
Hi, when i ran the demo/image/demo-coco.ipynb, i got a different result with the result in your paper. I just changed the test picture to "sample6.jpg".And i think the picture is same as the Figure.5 in the paper, isn't it?

**Comment by Wilbur529** [comment]
I got the result below, but the result showed in the Figure.5 is 12.
```
loading annotations into memory...
Done (t=7.15s)
creating index...
index created!
<function PeakResponseMapping._median_filter at 0x7f3154192ae8>
addedmodule5
enable_peak_stimulation on
***************************
Object count in the image:
    [class_idx: 22] zebra (11.00)
```

**Comment by GuoleiSun** [comment]
Hi,

Thanks for your interest. The trained weight we shared can be used to reproduce the evaluation metrics (mrmse and r-mrmse) in the paper. But we cann't guarantee it to reproduce the exact counts for specific images because it is retrained and different (due to randomness) from the weight we used to generate samples in the paper. Nevertheless, the difference should be small, like 12 vs 11.
