### ISSUE TITLE
How to understand ILC?

### ISSUE THREAD

**Issue by Wilbur529** [GuoleiSun/CountSeg#5]
Hi,  @GuoleiSun thanks for sharing the source code.  When i trained the model with VOC dataset, i thought it used the global object count as its label. So, how to understand ILC? I found it in the paper that you explained  as follows:

> Image-level supervised methods using only within subitizing range counts are denoted as ILC.

**Comment by GuoleiSun** [comment]
Hi,

Thanks for your interest. We don't use global object count even though we load it in the code. ILC simply means that the count annotations our method needs for images is either exact count (when count <=4) or a flag of many (when count>4). 

See when you are a annotator and you are asked to give count annotation for an image for a specific class. With a simple glance, you can easily give the exact count for that class if the count is no more than 4. However, if there are >4 objects of that class, in order to give the exact count, you need to count from 1 to 2,3,....  Actually, this is from psychology study referred in the paper. The range of counts (<=4) is called "subitizing range", referred in wiki: https://en.wikipedia.org/wiki/Subitizing

**Comment by GuoleiSun** [comment]
Continuing from above.
With a simple glance, if the count is >4, you, as a annotator, just need to give a flag of many objects for that image (**no need of exact count**). We think in this way, the annotation time can be largely reduced.

**Comment by Wilbur529** [comment]
@GuoleiSun Thanks for your careful reply:) So the ranking loss only works for penalizing the under counting when there are more than 5 objects in the image. Is that right?

**Comment by GuoleiSun** [comment]
Yes, correct. Thanks
